"""add serve safari booking support

Revision ID: 05cb419d89e2
Revises: 045f2e7f97fe
Create Date: 2026-08-26 19:46:15.019333

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '05cb419d89e2'
down_revision = '045f2e7f97fe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('serve_safari_booking_details',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('booking_id', sa.Integer(), nullable=False),
    sa.Column('organisation_name', sa.String(length=180), nullable=False),
    sa.Column('organisation_type', sa.String(length=80), nullable=True),
    sa.Column('mission_location', sa.String(length=255), nullable=False),
    sa.Column('mission_start_date', sa.Date(), nullable=True),
    sa.Column('mission_end_date', sa.Date(), nullable=True),
    sa.Column('arrival_flight_number', sa.String(length=80), nullable=True),
    sa.Column('arrival_date', sa.Date(), nullable=True),
    sa.Column('arrival_time', sa.Time(), nullable=True),
    sa.Column('departure_flight_number', sa.String(length=80), nullable=True),
    sa.Column('departure_date', sa.Date(), nullable=True),
    sa.Column('departure_time', sa.Time(), nullable=True),
    sa.Column('service_needs', sa.JSON(), nullable=False),
    sa.Column('transport_notes', sa.Text(), nullable=True),
    sa.Column('extra_details', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('serve_safari_booking_details', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_serve_safari_booking_details_booking_id'), ['booking_id'], unique=True)

    with op.batch_alter_table('packages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pricing_mode', sa.String(length=20), server_default='fixed', nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('packages', schema=None) as batch_op:
        batch_op.drop_column('pricing_mode')

    with op.batch_alter_table('serve_safari_booking_details', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_serve_safari_booking_details_booking_id'))

    op.drop_table('serve_safari_booking_details')
    # ### end Alembic commands ###
