"""add highlights and package category

Revision ID: 1495b9bad289
Revises: 429d6eb3c39e
Create Date: 2026-08-18 11:56:29.585728

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1495b9bad289'
down_revision = '429d6eb3c39e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('destinations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('highlights', sa.JSON(), server_default='[]', nullable=False))

    with op.batch_alter_table('packages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('highlights', sa.JSON(), server_default='[]', nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('packages', schema=None) as batch_op:
        batch_op.drop_column('highlights')
        batch_op.drop_column('category')

    with op.batch_alter_table('destinations', schema=None) as batch_op:
        batch_op.drop_column('highlights')

    # ### end Alembic commands ###
