"""add missing destination detail fields

Revision ID: 8c1ef77e5613
Revises: d2a8da241ab9
Create Date: 2026-08-26 10:45:20.225624

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8c1ef77e5613'
down_revision = 'd2a8da241ab9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('destinations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('recommended_stay', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('climate', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('wildlife_highlights', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('activities', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('getting_there', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('travel_tips', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('ideal_for', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('featured', sa.Boolean(), nullable=False, server_default=sa.false()))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('destinations', schema=None) as batch_op:
        batch_op.drop_column('featured')
        batch_op.drop_column('ideal_for')
        batch_op.drop_column('travel_tips')
        batch_op.drop_column('getting_there')
        batch_op.drop_column('activities')
        batch_op.drop_column('wildlife_highlights')
        batch_op.drop_column('climate')
        batch_op.drop_column('recommended_stay')

    # ### end Alembic commands ###
