"""add adults and children to bookings

Revision ID: 96db49b85395
Revises: f1a2b2367732
Create Date: 2026-08-20 11:27:22.207972

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '96db49b85395'
down_revision = 'f1a2b2367732'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('adults', sa.Integer(), nullable=False, server_default='1'))
        batch_op.add_column(sa.Column('children', sa.Integer(), nullable=False, server_default='0'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.drop_column('children')
        batch_op.drop_column('adults')

    # ### end Alembic commands ###
