"""add 7 and 8 pax package pricing

Revision ID: a5c3eccc08f1
Revises: 05cb419d89e2
Create Date: 2026-09-01 13:02:51.981892

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a5c3eccc08f1'
down_revision = '05cb419d89e2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('package_prices', schema=None) as batch_op:
        batch_op.add_column(sa.Column('price_7_pax', sa.Numeric(precision=10, scale=2), nullable=True))
        batch_op.add_column(sa.Column('price_8_pax', sa.Numeric(precision=10, scale=2), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('package_prices', schema=None) as batch_op:
        batch_op.drop_column('price_8_pax')
        batch_op.drop_column('price_7_pax')

    # ### end Alembic commands ###
