"""expand packages with itineraries and pricing

Revision ID: bb4485d194be
Revises: 1495b9bad289
Create Date: 2026-08-19 10:54:00.684274

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bb4485d194be'
down_revision = '1495b9bad289'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('package_itineraries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('package_id', sa.Integer(), nullable=False),
    sa.Column('day_number', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['package_id'], ['packages.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('package_prices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('package_id', sa.Integer(), nullable=False),
    sa.Column('season_name', sa.String(length=120), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('accommodation_level', sa.String(length=50), nullable=False),
    sa.Column('price_1_pax', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('price_2_pax', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('price_3_pax', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('price_4_pax', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('price_5_pax', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('price_6_pax', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['package_id'], ['packages.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('packages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('duration_nights', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column("inclusions", sa.JSON(), server_default="[]", nullable=False,))
        batch_op.add_column(sa.Column("exclusions", sa.JSON(), server_default="[]", nullable=False,))
        batch_op.add_column(sa.Column("optional_extras", sa.JSON(), server_default="[]", nullable=False,))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('packages', schema=None) as batch_op:
        batch_op.drop_column('optional_extras')
        batch_op.drop_column('exclusions')
        batch_op.drop_column('inclusions')
        batch_op.drop_column('duration_nights')

    op.drop_table('package_prices')
    op.drop_table('package_itineraries')
    # ### end Alembic commands ###
