"""expand destination travel information

Revision ID: d2a8da241ab9
Revises: 96db49b85395
Create Date: 2026-08-26 10:16:20.645514

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd2a8da241ab9'
down_revision = '96db49b85395'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('destinations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('best_time_to_visit', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('destinations', schema=None) as batch_op:
        batch_op.drop_column('best_time_to_visit')

    # ### end Alembic commands ###
