"""add child price to package prices

Revision ID: f1a2b2367732
Revises: 2986b0a9d1a2
Create Date: 2026-08-20 10:24:47.466031

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f1a2b2367732'
down_revision = '2986b0a9d1a2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('package_prices', schema=None) as batch_op:
        batch_op.add_column(sa.Column('child_price', sa.Numeric(precision=10, scale=2), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('package_prices', schema=None) as batch_op:
        batch_op.drop_column('child_price')

    # ### end Alembic commands ###
